"use client";

import Link from "next/link";
import { useQuery } from "convex/react";
import { useConvexAuth } from "convex/react";
import { useAuthActions } from "@convex-dev/auth/react";
// NOTE: ../convex/_generated is generated by `npx convex dev` (owned by the Convex agent).
import { api } from "../convex/_generated/api";

function SignInButton() {
  const { signIn } = useAuthActions();
  return (
    <button
      className="btn btn-primary"
      // Convex Auth Google provider id is "google".
      onClick={() => void signIn("google")}
    >
      Sign in with Google
    </button>
  );
}

function SignOutButton() {
  const { signOut } = useAuthActions();
  return (
    <button className="btn" onClick={() => void signOut()}>
      Sign out
    </button>
  );
}

function statusBadge(status: string) {
  const cls =
    status === "ready"
      ? "badge badge-ready"
      : status === "failed"
      ? "badge badge-failed"
      : "badge badge-processing";
  return <span className={cls}>{status}</span>;
}

function VideoGrid() {
  const videos = useQuery(api.videos.list);
  const isAdmin = useQuery(api.videos.isAdmin);

  return (
    <div className="container">
      <div className="topbar">
        <div className="brand">
          Video<span>Hub</span>
        </div>
        <div className="row">
          {isAdmin && (
            <Link className="btn" href="/admin">
              Admin
            </Link>
          )}
          <SignOutButton />
        </div>
      </div>

      {videos === undefined ? (
        <div className="empty">Loading…</div>
      ) : videos.length === 0 ? (
        <div className="empty">No videos yet. Check back soon.</div>
      ) : (
        <div className="grid">
          {videos.map((v) => {
            const ready = v.status === "ready";
            const inner = (
              <>
                <h3>{v.title}</h3>
                <p>{v.description}</p>
                {statusBadge(v.status)}
              </>
            );
            return ready ? (
              <Link key={v._id} className="card" href={`/videos/${v._id}`}>
                {inner}
              </Link>
            ) : (
              <div
                key={v._id}
                className="card"
                style={{ cursor: "default", opacity: 0.7 }}
              >
                {inner}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

export default function HomePage() {
  const { isAuthenticated, isLoading } = useConvexAuth();

  if (isLoading) {
    return <div className="center">Loading…</div>;
  }

  if (!isAuthenticated) {
    return (
      <div className="center">
        <div className="brand" style={{ fontSize: 34 }}>
          Video<span>Hub</span>
        </div>
        <p className="muted">Free video courses. Sign in to start watching.</p>
        <SignInButton />
      </div>
    );
  }

  return <VideoGrid />;
}
