"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useQuery, useAction } from "convex/react";
import VideoPlayer from "../../../components/VideoPlayer";
// NOTE: ../../../convex/_generated is generated by `npx convex dev`.
import { api } from "../../../convex/_generated/api";
import { Id } from "../../../convex/_generated/dataModel";

// Global platform apkId (public, baked into the player — exactly like window.apkId).
const APK_ID = process.env.NEXT_PUBLIC_APK_ID ?? "";

export default function VideoPage({ params }: { params: { id: string } }) {
  const videoId = params.id as Id<"videos">;
  // Display metadata only — no secrets, no URLs.
  const video = useQuery(api.videos.get, { id: videoId });
  // Mints a per-user stream token and returns the tokenized master playlist URL.
  const getStreamToken = useAction(api.videos.getStreamToken);

  const [masterUrl, setMasterUrl] = useState<string | null>(null);
  const [watermark, setWatermark] = useState<string>("");
  const [tokenError, setTokenError] = useState<string | null>(null);

  useEffect(() => {
    if (video && video.status === "ready" && !masterUrl) {
      getStreamToken({ videoId })
        .then((res) => {
          setMasterUrl(res.masterUrl);
          setWatermark(res.watermark);
        })
        .catch((e) => setTokenError(String(e)));
    }
  }, [video, masterUrl, getStreamToken, videoId]);

  return (
    <div className="container">
      <div className="topbar">
        <div className="brand">
          <Link href="/">
            Video<span>Hub</span>
          </Link>
        </div>
        <Link className="btn" href="/">
          Back
        </Link>
      </div>

      {video === undefined ? (
        <div className="empty">Loading…</div>
      ) : video === null ? (
        <div className="empty">Video not found.</div>
      ) : video.status !== "ready" ? (
        <div className="empty">
          This video is still {video.status}. Please check back soon.
        </div>
      ) : (
        <>
          <h1 style={{ marginBottom: 6 }}>{video.title}</h1>
          <p className="muted" style={{ marginTop: 0, marginBottom: 18 }}>
            {video.description}
          </p>
          {tokenError ? (
            <div className="empty" style={{ color: "var(--danger)" }}>
              Could not authorize playback: {tokenError}
            </div>
          ) : masterUrl ? (
            <VideoPlayer
              apkId={APK_ID}
              masterUrl={masterUrl}
              title={video.title}
              watermark={watermark}
            />
          ) : (
            <div className="empty">Authorizing playback…</div>
          )}
        </>
      )}
    </div>
  );
}
