"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useQuery, useAction } from "convex/react";
import VideoPlayer from "../../../components/VideoPlayer";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
// NOTE: ../../../convex/_generated is generated by `npx convex dev`.
import { api } from "../../../convex/_generated/api";
import { Id } from "../../../convex/_generated/dataModel";

// Global platform apkId (public, baked into the player — exactly like window.apkId).
const APK_ID = process.env.NEXT_PUBLIC_APK_ID ?? "";

/** Best-effort readable host for a resource URL (e.g. "drive.google.com").
 *  Returns "" for relative/invalid URLs so the UI can fall back gracefully. */
function hostFromUrl(url: string): string {
  try {
    return new URL(url).hostname.replace(/^www\./, "");
  } catch {
    return "";
  }
}

export default function VideoPage({ params }: { params: { id: string } }) {
  const videoId = params.id as Id<"videos">;
  // Display metadata only — no secrets, no URLs.
  const video = useQuery(api.videos.get, { id: videoId });
  // Mints a per-user stream token and returns the tokenized master playlist URL.
  const getStreamToken = useAction(api.videos.getStreamToken);

  const [masterUrl, setMasterUrl] = useState<string | null>(null);
  const [watermark, setWatermark] = useState<string>("");
  const [tokenError, setTokenError] = useState<string | null>(null);

  useEffect(() => {
    if (video && video.status === "ready" && !masterUrl) {
      getStreamToken({ videoId })
        .then((res) => {
          setMasterUrl(res.masterUrl);
          setWatermark(res.watermark);
        })
        .catch((e) => setTokenError(String(e)));
    }
  }, [video, masterUrl, getStreamToken, videoId]);

  // Reflect the video title in the browser tab.
  useEffect(() => {
    if (video?.title) {
      document.title = `${video.title} — VideoHub`;
    }
  }, [video?.title]);

  return (
    <div className="container">
      <header className="topbar">
        <div className="brand">
          <Link href="/">
            <span className="logo-mark" aria-hidden="true" />
            Video<span>Hub</span>
          </Link>
        </div>
        <Link className="btn" href="/">
          ← Back to library
        </Link>
      </header>

      <main className="watch-layout">
        {video === undefined ? (
          <div aria-busy="true" aria-label="Loading video">
            <div
              className="skeleton skeleton-block"
              style={{ height: 34, maxWidth: 420, marginBottom: 18 }}
            />
            <div
              className="skeleton skeleton-block"
              style={{ height: 96, marginBottom: 24 }}
            />
            <div className="skeleton skeleton-block" style={{ aspectRatio: "16 / 9" }} />
          </div>
        ) : video === null ? (
          <div className="empty">
            <div className="empty-icon" aria-hidden="true">
              🔍
            </div>
            <p className="empty-title">Video not found</p>
            <p>It may have been removed or the link is incorrect.</p>
            <Link className="btn" href="/">
              Back to library
            </Link>
          </div>
        ) : video.status !== "ready" ? (
          <div className="empty">
            <div className="empty-icon" aria-hidden="true">
              ⏳
            </div>
            <p className="empty-title">Not ready yet</p>
            <p>This video is still {video.status}. Please check back soon.</p>
          </div>
        ) : (
          <>
            <h1 className="video-title">{video.title}</h1>
            {video.description ? (
              <section className="video-desc" aria-label="Video description">
                <h2 className="video-desc-label">Description</h2>
                <div className="video-desc-body">
                  <ReactMarkdown
                    remarkPlugins={[remarkGfm]}
                    components={{
                      // Open any links in a new tab, safely.
                      a: (props) => (
                        <a {...props} target="_blank" rel="noopener noreferrer" />
                      ),
                    }}
                  >
                    {video.description}
                  </ReactMarkdown>
                </div>
              </section>
            ) : null}
            {video.resources?.length ? (
              <section className="video-resources" aria-labelledby="resources-heading">
                <div className="resources-head">
                  <span className="resources-head-icon" aria-hidden="true">
                    <svg
                      viewBox="0 0 24 24"
                      width="16"
                      height="16"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <path d="M21.44 11.05 12.25 20.24a5 5 0 0 1-7.07-7.07l9.19-9.19a3.5 3.5 0 0 1 4.95 4.95l-9.2 9.19a2 2 0 0 1-2.83-2.83l8.49-8.48" />
                    </svg>
                  </span>
                  <h2 id="resources-heading" className="resources-head-title">
                    Attachments
                  </h2>
                  <span className="resources-count" aria-hidden="true">
                    {video.resources.length}
                  </span>
                </div>
                <ul className="resource-list">
                  {video.resources.map((r, i) => {
                    const host = hostFromUrl(r.url);
                    return (
                      <li key={i}>
                        <a
                          className="resource-card"
                          href={r.url}
                          target="_blank"
                          rel="noopener noreferrer"
                        >
                          <span className="resource-icon" aria-hidden="true">
                            <svg
                              viewBox="0 0 24 24"
                              width="20"
                              height="20"
                              fill="none"
                              stroke="currentColor"
                              strokeWidth="2"
                              strokeLinecap="round"
                              strokeLinejoin="round"
                            >
                              <path d="M14 3v4a1 1 0 0 0 1 1h4" />
                              <path d="M17 21H7a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h7l5 5v11a2 2 0 0 1-2 2z" />
                              <line x1="9" y1="13" x2="15" y2="13" />
                              <line x1="9" y1="17" x2="13" y2="17" />
                            </svg>
                          </span>
                          <span className="resource-body">
                            <span className="resource-label">{r.label}</span>
                            <span className="resource-meta">
                              {host ? host : "External link"}
                              <span className="sr-only"> (opens in a new tab)</span>
                            </span>
                          </span>
                          <span className="resource-ext" aria-hidden="true">
                            <svg
                              viewBox="0 0 24 24"
                              width="15"
                              height="15"
                              fill="none"
                              stroke="currentColor"
                              strokeWidth="2.2"
                              strokeLinecap="round"
                              strokeLinejoin="round"
                            >
                              <path d="M7 17 17 7" />
                              <path d="M8 7h9v9" />
                            </svg>
                          </span>
                        </a>
                      </li>
                    );
                  })}
                </ul>
              </section>
            ) : null}
            {tokenError ? (
              <div className="alert alert-danger" role="alert">
                <span aria-hidden="true">⚠️</span>
                <span>Could not authorize playback: {tokenError}</span>
              </div>
            ) : masterUrl ? (
              <VideoPlayer
                apkId={APK_ID}
                masterUrl={masterUrl}
                title={video.title}
                watermark={watermark}
              />
            ) : (
              <div>
                {/* Same fixed 16:9 footprint as the player so nothing jumps. */}
                <div
                  className="skeleton skeleton-block"
                  style={{ aspectRatio: "16 / 9" }}
                  role="status"
                  aria-label="Authorizing playback"
                />
                <p className="muted" style={{ marginTop: 12, textAlign: "center" }}>
                  Authorizing playback…
                </p>
              </div>
            )}
          </>
        )}
      </main>
    </div>
  );
}
