"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { useAction, useMutation, useQuery } from "convex/react";
// NOTE: ../convex/_generated is generated by `npx convex dev`.
import { api } from "../../convex/_generated/api";
import { Id } from "../../convex/_generated/dataModel";

export default function AdminPage() {
  const isAdmin = useQuery(api.videos.isAdmin);
  const generateRawUploadUrl = useMutation(api.videos.generateRawUploadUrl);
  const createVideo = useAction(api.videos.createVideo);

  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [file, setFile] = useState<File | null>(null);
  const [busy, setBusy] = useState(false);
  const [msg, setMsg] = useState<string | null>(null);
  const [err, setErr] = useState<string | null>(null);

  async function onSubmit(e: FormEvent) {
    e.preventDefault();
    setErr(null);
    setMsg(null);
    if (!file) {
      setErr("Please choose a video file.");
      return;
    }
    if (!title.trim()) {
      setErr("Please enter a title.");
      return;
    }

    setBusy(true);
    try {
      // 1) Ask Convex for a one-time raw upload URL (admin-only mutation).
      const uploadUrl = await generateRawUploadUrl();

      // 2) POST the raw file bytes directly to Convex storage.
      const res = await fetch(uploadUrl, {
        method: "POST",
        headers: { "Content-Type": file.type || "application/octet-stream" },
        body: file,
      });
      if (!res.ok) {
        throw new Error(`Upload failed (${res.status})`);
      }
      const { storageId } = (await res.json()) as { storageId: string };

      // 3) Kick off processing. createVideo inserts the doc and fires the
      //    backend /process job; it returns immediately with the videoId.
      await createVideo({
        rawStorageId: storageId as Id<"_storage">,
        title: title.trim(),
        description: description.trim(),
      });

      setMsg("Uploaded. Processing has started — the video will appear once ready.");
      setTitle("");
      setDescription("");
      setFile(null);
      // Reset the file input element.
      (e.target as HTMLFormElement).reset();
    } catch (e2: any) {
      setErr(e2?.message ?? "Something went wrong.");
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="container">
      <div className="topbar">
        <div className="brand">
          <Link href="/">
            Video<span>Hub</span>
          </Link>
        </div>
        <Link className="btn" href="/">
          Back
        </Link>
      </div>

      {isAdmin === undefined ? (
        <div className="empty">Loading…</div>
      ) : !isAdmin ? (
        <div className="empty">Not authorized.</div>
      ) : (
        <>
          <h1>Upload a video</h1>
          <form className="form" onSubmit={onSubmit}>
            <div className="field">
              <label htmlFor="title">Title</label>
              <input
                id="title"
                type="text"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="Intro to something"
              />
            </div>

            <div className="field">
              <label htmlFor="description">Description</label>
              <textarea
                id="description"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="What this video covers…"
              />
            </div>

            <div className="field">
              <label htmlFor="file">Video file</label>
              <input
                id="file"
                type="file"
                accept="video/*"
                onChange={(e) => setFile(e.target.files?.[0] ?? null)}
              />
            </div>

            <button className="btn btn-primary" type="submit" disabled={busy}>
              {busy ? "Uploading…" : "Upload"}
            </button>

            {msg && (
              <p className="muted" style={{ marginTop: 14 }}>
                {msg}
              </p>
            )}
            {err && (
              <p style={{ marginTop: 14, color: "var(--danger)" }}>{err}</p>
            )}
          </form>
        </>
      )}
    </div>
  );
}
