"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { useAction, useMutation, useQuery } from "convex/react";
// NOTE: ../convex/_generated is generated by `npx convex dev`.
import { api } from "../../convex/_generated/api";
import { Id } from "../../convex/_generated/dataModel";

export default function AdminPage() {
  const isAdmin = useQuery(api.videos.isAdmin);
  const generateRawUploadUrl = useMutation(api.videos.generateRawUploadUrl);
  const createVideo = useAction(api.videos.createVideo);

  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [file, setFile] = useState<File | null>(null);
  // Generic external attachments: label + url rows the admin can add/remove.
  const [resources, setResources] = useState<{ label: string; url: string }[]>([]);
  const [busy, setBusy] = useState(false);
  const [msg, setMsg] = useState<string | null>(null);
  const [err, setErr] = useState<string | null>(null);

  function addResource() {
    setResources((rows) => [...rows, { label: "", url: "" }]);
  }

  function removeResource(index: number) {
    setResources((rows) => rows.filter((_, i) => i !== index));
  }

  function updateResource(index: number, field: "label" | "url", value: string) {
    setResources((rows) =>
      rows.map((row, i) => (i === index ? { ...row, [field]: value } : row)),
    );
  }

  async function onSubmit(e: FormEvent) {
    e.preventDefault();
    setErr(null);
    setMsg(null);
    if (!file) {
      setErr("Please choose a video file.");
      return;
    }
    if (!title.trim()) {
      setErr("Please enter a title.");
      return;
    }

    setBusy(true);
    try {
      // 1) Ask Convex for a one-time raw upload URL (admin-only mutation).
      const uploadUrl = await generateRawUploadUrl();

      // 2) POST the raw file bytes directly to Convex storage.
      const res = await fetch(uploadUrl, {
        method: "POST",
        headers: { "Content-Type": file.type || "application/octet-stream" },
        body: file,
      });
      if (!res.ok) {
        throw new Error(`Upload failed (${res.status})`);
      }
      const { storageId } = (await res.json()) as { storageId: string };

      // Only keep rows where both the label and the url are filled in.
      const cleanResources = resources
        .map((r) => ({ label: r.label.trim(), url: r.url.trim() }))
        .filter((r) => r.label && r.url);

      // 3) Kick off processing. createVideo inserts the doc and fires the
      //    backend /process job; it returns immediately with the videoId.
      await createVideo({
        rawStorageId: storageId as Id<"_storage">,
        title: title.trim(),
        description: description.trim(),
        ...(cleanResources.length ? { resources: cleanResources } : {}),
      });

      setMsg("Uploaded. Processing has started — the video will appear once ready.");
      setTitle("");
      setDescription("");
      setFile(null);
      setResources([]);
      // Reset the file input element.
      (e.target as HTMLFormElement).reset();
    } catch (e2: any) {
      setErr(e2?.message ?? "Something went wrong.");
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="container">
      <header className="topbar">
        <div className="brand">
          <Link href="/">
            <span className="logo-mark" aria-hidden="true" />
            Video<span>Hub</span>
          </Link>
        </div>
        <Link className="btn" href="/">
          ← Back to library
        </Link>
      </header>

      <main>
        {isAdmin === undefined ? (
          <div className="center" style={{ minHeight: "40vh" }} role="status">
            <div className="spinner" />
            <p className="muted">Loading…</p>
          </div>
        ) : !isAdmin ? (
          <div className="empty">
            <div className="empty-icon" aria-hidden="true">
              🔒
            </div>
            <p className="empty-title">Not authorized</p>
            <p>This page is for admins only.</p>
            <Link className="btn" href="/">
              Back to library
            </Link>
          </div>
        ) : (
          <>
            <div className="page-head">
              <div>
                <h1 className="page-title">Upload a video</h1>
                <p className="page-sub">
                  The video is encrypted and packaged for streaming after upload.
                </p>
              </div>
            </div>
            <form className="form" onSubmit={onSubmit}>
              <div className="field">
                <label htmlFor="title">Title</label>
                <input
                  id="title"
                  type="text"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder="Intro to something"
                  required
                />
              </div>

              <div className="field">
                <label htmlFor="description">Description</label>
                <textarea
                  id="description"
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="What this video covers…"
                />
                <span className="field-hint">
                  Markdown is supported (headings, lists, links, tables…).
                </span>
              </div>

              <div className="field">
                <label>Resources / Attachments</label>
                {resources.map((r, i) => (
                  <div className="resource-row" key={i}>
                    <input
                      type="text"
                      aria-label={`Resource ${i + 1} label`}
                      value={r.label}
                      onChange={(e) => updateResource(i, "label", e.target.value)}
                      placeholder="Label (e.g. Course overview PDF)"
                    />
                    <input
                      type="url"
                      aria-label={`Resource ${i + 1} URL`}
                      value={r.url}
                      onChange={(e) => updateResource(i, "url", e.target.value)}
                      placeholder="https://…"
                    />
                    <button
                      type="button"
                      className="btn resource-remove"
                      aria-label={`Remove resource ${i + 1}`}
                      onClick={() => removeResource(i)}
                    >
                      ×
                    </button>
                  </div>
                ))}
                <button type="button" className="btn" onClick={addResource}>
                  + Add resource
                </button>
                <span className="field-hint">
                  Optional external links (PDFs, docs, Drive…) shown below the
                  description on the watch page. Rows missing a label or URL are
                  ignored.
                </span>
              </div>

              <div className="field">
                <label htmlFor="file">Video file</label>
                <input
                  id="file"
                  type="file"
                  accept="video/*"
                  onChange={(e) => setFile(e.target.files?.[0] ?? null)}
                  required
                />
              </div>

              <button className="btn btn-primary" type="submit" disabled={busy}>
                {busy ? "Uploading…" : "Upload"}
              </button>

              {msg && (
                <div className="alert alert-success" role="status">
                  <span aria-hidden="true">✓</span>
                  <span>{msg}</span>
                </div>
              )}
              {err && (
                <div className="alert alert-danger" role="alert">
                  <span aria-hidden="true">⚠️</span>
                  <span>{err}</span>
                </div>
              )}
            </form>
          </>
        )}
      </main>
    </div>
  );
}
