"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useQuery, useAction } from "convex/react";
import VideoPlayer from "../../../components/VideoPlayer";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
// NOTE: ../../../convex/_generated is generated by `npx convex dev`.
import { api } from "../../../convex/_generated/api";
import { Id } from "../../../convex/_generated/dataModel";

// Global platform apkId (public, baked into the player — exactly like window.apkId).
const APK_ID = process.env.NEXT_PUBLIC_APK_ID ?? "";

export default function VideoPage({ params }: { params: { id: string } }) {
  const videoId = params.id as Id<"videos">;
  // Display metadata only — no secrets, no URLs.
  const video = useQuery(api.videos.get, { id: videoId });
  // Mints a per-user stream token and returns the tokenized master playlist URL.
  const getStreamToken = useAction(api.videos.getStreamToken);

  const [masterUrl, setMasterUrl] = useState<string | null>(null);
  const [watermark, setWatermark] = useState<string>("");
  const [tokenError, setTokenError] = useState<string | null>(null);

  useEffect(() => {
    if (video && video.status === "ready" && !masterUrl) {
      getStreamToken({ videoId })
        .then((res) => {
          setMasterUrl(res.masterUrl);
          setWatermark(res.watermark);
        })
        .catch((e) => setTokenError(String(e)));
    }
  }, [video, masterUrl, getStreamToken, videoId]);

  // Reflect the video title in the browser tab.
  useEffect(() => {
    if (video?.title) {
      document.title = `${video.title} — VideoHub`;
    }
  }, [video?.title]);

  return (
    <div className="container">
      <header className="topbar">
        <div className="brand">
          <Link href="/">
            <span className="logo-mark" aria-hidden="true" />
            Video<span>Hub</span>
          </Link>
        </div>
        <Link className="btn" href="/">
          ← Back to library
        </Link>
      </header>

      <main className="watch-layout">
        {video === undefined ? (
          <div aria-busy="true" aria-label="Loading video">
            <div
              className="skeleton skeleton-block"
              style={{ height: 34, maxWidth: 420, marginBottom: 18 }}
            />
            <div
              className="skeleton skeleton-block"
              style={{ height: 96, marginBottom: 24 }}
            />
            <div className="skeleton skeleton-block" style={{ aspectRatio: "16 / 9" }} />
          </div>
        ) : video === null ? (
          <div className="empty">
            <div className="empty-icon" aria-hidden="true">
              🔍
            </div>
            <p className="empty-title">Video not found</p>
            <p>It may have been removed or the link is incorrect.</p>
            <Link className="btn" href="/">
              Back to library
            </Link>
          </div>
        ) : video.status !== "ready" ? (
          <div className="empty">
            <div className="empty-icon" aria-hidden="true">
              ⏳
            </div>
            <p className="empty-title">Not ready yet</p>
            <p>This video is still {video.status}. Please check back soon.</p>
          </div>
        ) : (
          <>
            <h1 className="video-title">{video.title}</h1>
            {video.description ? (
              <section className="video-desc" aria-label="Video description">
                <h2 className="video-desc-label">Description</h2>
                <div className="video-desc-body">
                  <ReactMarkdown
                    remarkPlugins={[remarkGfm]}
                    components={{
                      // Open any links in a new tab, safely.
                      a: (props) => (
                        <a {...props} target="_blank" rel="noopener noreferrer" />
                      ),
                    }}
                  >
                    {video.description}
                  </ReactMarkdown>
                </div>
              </section>
            ) : null}
            {video.resources?.length ? (
              <section className="video-resources" aria-label="Resources">
                <h2 className="video-desc-label">Resources</h2>
                <ul className="resource-list">
                  {video.resources.map((r, i) => (
                    <li key={i}>
                      <a
                        className="resource-card"
                        href={r.url}
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        <span className="resource-icon" aria-hidden="true">
                          📎
                        </span>
                        <span className="resource-label">{r.label}</span>
                        <span className="resource-ext" aria-hidden="true">
                          ↗
                        </span>
                      </a>
                    </li>
                  ))}
                </ul>
              </section>
            ) : null}
            {tokenError ? (
              <div className="alert alert-danger" role="alert">
                <span aria-hidden="true">⚠️</span>
                <span>Could not authorize playback: {tokenError}</span>
              </div>
            ) : masterUrl ? (
              <VideoPlayer
                apkId={APK_ID}
                masterUrl={masterUrl}
                title={video.title}
                watermark={watermark}
              />
            ) : (
              <div>
                {/* Same fixed 16:9 footprint as the player so nothing jumps. */}
                <div
                  className="skeleton skeleton-block"
                  style={{ aspectRatio: "16 / 9" }}
                  role="status"
                  aria-label="Authorizing playback"
                />
                <p className="muted" style={{ marginTop: 12, textAlign: "center" }}>
                  Authorizing playback…
                </p>
              </div>
            )}
          </>
        )}
      </main>
    </div>
  );
}
